apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argocd-springboot-demo2
  description: Demo Springboot application
  labels:
    example.com/custom: custom_label_value
  annotations:
    example.com/service-discovery: rgocd-springboot-demo2
    circleci.com/project-slug: github/example-org/artist-website
  tags:
    - java
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: website
  lifecycle: production
  owner: artist-relations-team
  system: public-websites
